/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    projects: Project;
    lead: Lead;
    media: Media;
    blogs: Blog;
    waitlists: Waitlist;
    documents: Document;
    stacks: Stack;
    issues: Issue;
    types: Type;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    lead: LeadSelect<false> | LeadSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    waitlists: WaitlistsSelect<false> | WaitlistsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    stacks: StacksSelect<false> | StacksSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    types: TypesSelect<false> | TypesSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  profilePicture?: (number | null) | Media;
  type: "developer" | "startup" | "lead";
  phoneNumber?: string | null;
  country?:
    | (
        | "AF"
        | "AX"
        | "AL"
        | "DZ"
        | "AS"
        | "AD"
        | "AO"
        | "AI"
        | "AQ"
        | "AG"
        | "AR"
        | "AM"
        | "AW"
        | "AU"
        | "AT"
        | "AZ"
        | "BS"
        | "BH"
        | "BD"
        | "BB"
        | "BY"
        | "BE"
        | "BZ"
        | "BJ"
        | "BM"
        | "BT"
        | "BO"
        | "BA"
        | "BW"
        | "BV"
        | "BR"
        | "IO"
        | "BN"
        | "BG"
        | "BF"
        | "BI"
        | "KH"
        | "CM"
        | "CA"
        | "CV"
        | "KY"
        | "CF"
        | "TD"
        | "CL"
        | "CN"
        | "CX"
        | "CC"
        | "CO"
        | "KM"
        | "CG"
        | "CD"
        | "CK"
        | "CR"
        | "CI"
        | "HR"
        | "CU"
        | "CY"
        | "CZ"
        | "DK"
        | "DJ"
        | "DM"
        | "DO"
        | "EC"
        | "EG"
        | "SV"
        | "GQ"
        | "ER"
        | "EE"
        | "ET"
        | "FK"
        | "FO"
        | "FJ"
        | "FI"
        | "FR"
        | "GF"
        | "PF"
        | "TF"
        | "GA"
        | "GM"
        | "GE"
        | "DE"
        | "GH"
        | "GI"
        | "GR"
        | "GL"
        | "GD"
        | "GP"
        | "GU"
        | "GT"
        | "GG"
        | "GN"
        | "GW"
        | "GY"
        | "HT"
        | "HM"
        | "VA"
        | "HN"
        | "HK"
        | "HU"
        | "IS"
        | "IN"
        | "ID"
        | "IR"
        | "IQ"
        | "IE"
        | "IM"
        | "IL"
        | "IT"
        | "JM"
        | "JP"
        | "JE"
        | "JO"
        | "KZ"
        | "KE"
        | "KI"
        | "KP"
        | "KR"
        | "KW"
        | "KG"
        | "LA"
        | "LV"
        | "LB"
        | "LS"
        | "LR"
        | "LY"
        | "LI"
        | "LT"
        | "LU"
        | "MO"
        | "MK"
        | "MG"
        | "MW"
        | "MY"
        | "MV"
        | "ML"
        | "MT"
        | "MH"
        | "MQ"
        | "MR"
        | "MU"
        | "YT"
        | "MX"
        | "FM"
        | "MD"
        | "MC"
        | "MN"
        | "MS"
        | "MA"
        | "MZ"
        | "MM"
        | "NA"
        | "NR"
        | "NP"
        | "NL"
        | "AN"
        | "NC"
        | "NZ"
        | "NI"
        | "NE"
        | "NG"
        | "NU"
        | "NF"
        | "MP"
        | "NO"
        | "OM"
        | "PK"
        | "PW"
        | "PS"
        | "PA"
        | "PG"
        | "PY"
        | "PE"
        | "PH"
        | "PN"
        | "PL"
        | "PT"
        | "PR"
        | "QA"
        | "RE"
        | "RO"
        | "RU"
        | "RW"
        | "SH"
        | "KN"
        | "LC"
        | "PM"
        | "VC"
        | "WS"
        | "SM"
        | "ST"
        | "SA"
        | "SN"
        | "CS"
        | "SC"
        | "SL"
        | "SG"
        | "SK"
        | "SI"
        | "SB"
        | "SO"
        | "ZA"
        | "GS"
        | "ES"
        | "LK"
        | "SD"
        | "SR"
        | "SJ"
        | "SZ"
        | "SE"
        | "CH"
        | "SY"
        | "TW"
        | "TJ"
        | "TZ"
        | "TH"
        | "TL"
        | "TG"
        | "TK"
        | "TO"
        | "TT"
        | "TN"
        | "TR"
        | "TM"
        | "TC"
        | "TV"
        | "UG"
        | "UA"
        | "AE"
        | "GB"
        | "US"
        | "UM"
        | "UY"
        | "UZ"
        | "VU"
        | "VE"
        | "VN"
        | "VG"
        | "VI"
        | "WF"
        | "EH"
        | "YE"
        | "ZM"
        | "ZW"
      )
    | null;
  role?: ("admin" | "user") | null;
  githubId?: string | null;
  wallet?: number | null;
  transactions?:
    | {
        transactionDate?: string | null;
        transactionAmount?: number | null;
        transactionType?: ("income" | "withdrawal" | "tip") | null;
        transactionMethods?:
          | ("credit_card" | "bank_transfer" | "crypto")
          | null;
        transactionStatus?: ("pending" | "completed" | "failed") | null;
        transactionProject?: (number | null) | Project;
        transactionDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  developerFields?: {
    bio?: string | null;
    issues?: (number | Issue)[] | null;
    totalPayment?: number | null;
    withdrawableAmount?: number | null;
    payments?:
      | {
          paymentDate?: string | null;
          paymentAmount?: number | null;
          paymentType?: ("income" | "withdrawal" | "tip") | null;
          paymentMethod?: string | null;
          paymentStatus?: ("pending" | "completed" | "failed") | null;
          paymentReference?: string | null;
          paymentDescription?: string | null;
          id?: string | null;
        }[]
      | null;
    dateJoined?: string | null;
    profilePicture?: (number | null) | Media;
    skills?:
      | {
          skill?: string | null;
          id?: string | null;
        }[]
      | null;
    experienceLevel?:
      | ("junior" | "mid_level" | "senior" | "lead" | "architect")
      | null;
    githubProfile?: string | null;
    linkedinProfile?: string | null;
    personalWebsite?: string | null;
    primaryRole?:
      | (
          | "Frontend Developer"
          | "Backend Developer"
          | "Full Stack Developer"
          | "Mobile Developer"
          | "DevOps Engineer"
          | "Data Scientist"
          | "UI/UX Designer"
          | "QA Engineer"
          | "Other"
        )
      | null;
    availability?:
      | ("full_time" | "part_time" | "contract" | "freelance" | "not_available")
      | null;
    preferredWorkType?: ("remote" | "on_site" | "hybrid") | null;
    education?:
      | {
          degree?: string | null;
          institution?: string | null;
          graduationYear?: number | null;
          id?: string | null;
        }[]
      | null;
    languages?:
      | {
          language?: string | null;
          proficiency?:
            | ("Beginner" | "Intermediate" | "Advanced" | "Native")
            | null;
          id?: string | null;
        }[]
      | null;
    hourlyRate?: number | null;
    preferredProjectDuration?:
      | (
          | "Less than 1 month"
          | "1-3 months"
          | "3-6 months"
          | "6-12 months"
          | "More than 12 months"
        )
      | null;
    stripeAccountId?: string | null;
    stripeOnboardingUrl?: string | null;
    stripeAccountStatus?:
      | ("pending" | "active" | "restricted" | "disabled")
      | null;
    assessment?: {
      languages?:
        | {
            language?:
              | (
                  | "typescript"
                  | "javascript"
                  | "python"
                  | "java"
                  | "ruby"
                  | "go"
                  | "rust"
                  | "c++"
                  | "c#"
                  | "php"
                  | "swift"
                  | "kotlin"
                  | "dart"
                  | "elixir"
                  | "erlang"
                  | "haskell"
                  | "scala"
                  | "ocaml"
                )
              | null;
            id?: string | null;
          }[]
        | null;
      categories?:
        | {
            category?:
              | (
                  | "web3"
                  | "fintech"
                  | "saas"
                  | "ai/ml"
                  | "mobile"
                  | "devops"
                  | "security"
                  | "ecommerce"
                )
              | null;
            id?: string | null;
          }[]
        | null;
      timeManagement?: {
        selectedOption?: string | null;
        style?: string | null;
        strengths?:
          | {
              strength?: string | null;
              id?: string | null;
            }[]
          | null;
        weaks?:
          | {
              weak?: string | null;
              id?: string | null;
            }[]
          | null;
        recommendation?: string | null;
      };
      technical?: {
        title?: string | null;
        diff?: ("easy" | "medium" | "hard") | null;
        estTime?: number | null;
        context?: string | null;
        requirements?:
          | {
              requirement?: string | null;
              id?: string | null;
            }[]
          | null;
        code?: string | null;
        challengeId?: string | null;
        submittedAt?: string | null;
        timeSpent?: number | null;
        passed?: boolean | null;
        score?: number | null;
      };
    };
  };
  startupFields?: {
    companyName?: string | null;
    description?: string | null;
    foundingDate?: string | null;
    cto?: (number | null) | User;
    fundingInformation?: {
      fundingStage?:
        | ("Pre-seed" | "Seed" | "Series A" | "Series B" | "Series C+")
        | null;
      totalFundingRaised?: number | null;
      lastFundingDate?: string | null;
    };
    teamSize?: ("1-10" | "10-50" | "50-100" | "+100") | null;
    productStage?:
      | ("Idea" | "Prototype" | "MVP" | "Beta" | "Launched" | "Growth")
      | null;
  };
  leadFields?: {
    experience?: number | null;
    stack: (number | Stack)[];
    title?: string | null;
    location?: string | null;
    availability?: boolean | null;
    preferredProjectDuration?:
      | (
          | "Less than 1 month"
          | "1-3 months"
          | "3-6 months"
          | "6-12 months"
          | "More than 12 months"
        )[]
      | null;
    preferedPayment?: ("hourly" | "dcm") | null;
    hourlyRate?: number | null;
    projects?: (number | Project)[] | null;
  };
  website?: string | null;
  contactInformation?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  projects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  slug?: string | null;
  lead?: (number | null) | Lead;
  projectType?: ("normal" | "urgent" | "featured" | "trending") | null;
  startDate: string;
  endDate?: string | null;
  stacks?: (number | Stack)[] | null;
  status: "planned" | "in-progress" | "completed" | "on-hold";
  budget?: number | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  collabuters?:
    | {
        collabuter?: (number | null) | User;
        status?: ("active" | "inactive") | null;
        id?: string | null;
      }[]
    | null;
  issues?: (number | Issue)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks".
 */
export interface Stack {
  id: number;
  name: string;
  description?: string | null;
  popularity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  type?: ("feature" | "bug") | null;
  category?:
    | (
        | "backend"
        | "frontend"
        | "application"
        | "ai"
        | "data"
        | "machineLearning"
        | "devops"
        | "security"
        | "database"
        | "qualityAssurance"
        | "documentation"
        | "seo"
      )[]
    | null;
  onboardingVideoLink?: string | null;
  onboardingVideo?: (number | null) | Media;
  onboardingVideoThumbnail?: (number | null) | Media;
  status: "open" | "in_progress" | "resolved" | "closed";
  requests?:
    | {
        requestTitle?: string | null;
        requestDescription?: string | null;
        requestType?: ("feature" | "bug") | null;
        requestPriority?: ("low" | "medium") | null;
        requestAssignee?: (number | null) | User;
        requestStatus?: ("pending" | "in_progress" | "completed") | null;
        id?: string | null;
      }[]
    | null;
  priority: "low" | "medium" | "high" | "urgent";
  budget?: number | null;
  assignees?: (number | User)[] | null;
  reporter: number | User;
  isBookmarked?: boolean | null;
  createdAt: string;
  updatedAt: string;
  project: number | Project;
  labels?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead".
 */
export interface Lead {
  id: number;
  name: string;
  profilePicture?: (number | null) | Media;
  experience: number;
  stack: (number | Stack)[];
  projects?: (number | Project)[] | null;
  availability?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  slug?: string | null;
  title: string;
  image: number | Media;
  description: string;
  richtext?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists".
 */
export interface Waitlist {
  id: number;
  fullName: string;
  email: string;
  userType: "developer" | "startup" | "other";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  description?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  stacks?: (number | null) | Stack;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types".
 */
export interface Type {
  id: number;
  name?: string | null;
  description?: string | null;
  icon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "projects";
        value: number | Project;
      } | null)
    | ({
        relationTo: "lead";
        value: number | Lead;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "blogs";
        value: number | Blog;
      } | null)
    | ({
        relationTo: "waitlists";
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: "documents";
        value: number | Document;
      } | null)
    | ({
        relationTo: "stacks";
        value: number | Stack;
      } | null)
    | ({
        relationTo: "issues";
        value: number | Issue;
      } | null)
    | ({
        relationTo: "types";
        value: number | Type;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  type?: T;
  phoneNumber?: T;
  country?: T;
  role?: T;
  githubId?: T;
  wallet?: T;
  transactions?:
    | T
    | {
        transactionDate?: T;
        transactionAmount?: T;
        transactionType?: T;
        transactionMethods?: T;
        transactionStatus?: T;
        transactionProject?: T;
        transactionDescription?: T;
        id?: T;
      };
  developerFields?:
    | T
    | {
        bio?: T;
        issues?: T;
        totalPayment?: T;
        withdrawableAmount?: T;
        payments?:
          | T
          | {
              paymentDate?: T;
              paymentAmount?: T;
              paymentType?: T;
              paymentMethod?: T;
              paymentStatus?: T;
              paymentReference?: T;
              paymentDescription?: T;
              id?: T;
            };
        dateJoined?: T;
        profilePicture?: T;
        skills?:
          | T
          | {
              skill?: T;
              id?: T;
            };
        experienceLevel?: T;
        githubProfile?: T;
        linkedinProfile?: T;
        personalWebsite?: T;
        primaryRole?: T;
        availability?: T;
        preferredWorkType?: T;
        education?:
          | T
          | {
              degree?: T;
              institution?: T;
              graduationYear?: T;
              id?: T;
            };
        languages?:
          | T
          | {
              language?: T;
              proficiency?: T;
              id?: T;
            };
        hourlyRate?: T;
        preferredProjectDuration?: T;
        stripeAccountId?: T;
        stripeOnboardingUrl?: T;
        stripeAccountStatus?: T;
        assessment?:
          | T
          | {
              languages?:
                | T
                | {
                    language?: T;
                    id?: T;
                  };
              categories?:
                | T
                | {
                    category?: T;
                    id?: T;
                  };
              timeManagement?:
                | T
                | {
                    selectedOption?: T;
                    style?: T;
                    strengths?:
                      | T
                      | {
                          strength?: T;
                          id?: T;
                        };
                    weaks?:
                      | T
                      | {
                          weak?: T;
                          id?: T;
                        };
                    recommendation?: T;
                  };
              technical?:
                | T
                | {
                    title?: T;
                    diff?: T;
                    estTime?: T;
                    context?: T;
                    requirements?:
                      | T
                      | {
                          requirement?: T;
                          id?: T;
                        };
                    code?: T;
                    challengeId?: T;
                    submittedAt?: T;
                    timeSpent?: T;
                    passed?: T;
                    score?: T;
                  };
            };
      };
  startupFields?:
    | T
    | {
        companyName?: T;
        description?: T;
        foundingDate?: T;
        cto?: T;
        fundingInformation?:
          | T
          | {
              fundingStage?: T;
              totalFundingRaised?: T;
              lastFundingDate?: T;
            };
        teamSize?: T;
        productStage?: T;
      };
  website?: T;
  contactInformation?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  projects?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  lead?: T;
  projectType?: T;
  startDate?: T;
  endDate?: T;
  stacks?: T;
  status?: T;
  budget?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  collabuters?:
    | T
    | {
        collabuter?: T;
        status?: T;
        id?: T;
      };
  issues?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_select".
 */
export interface LeadSelect<T extends boolean = true> {
  name?: T;
  experience?: T;
  stack?: T;
  projects?: T;
  availability?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  image?: T;
  description?: T;
  richtext?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists_select".
 */
export interface WaitlistsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  userType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  stacks?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks_select".
 */
export interface StacksSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  popularity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  category?: T;
  onboardingVideoLink?: T;
  onboardingVideo?: T;
  onboardingVideoThumbnail?: T;
  status?: T;
  requests?:
    | T
    | {
        requestTitle?: T;
        requestDescription?: T;
        requestType?: T;
        requestPriority?: T;
        requestAssignee?: T;
        requestStatus?: T;
        id?: T;
      };
  priority?: T;
  budget?: T;
  assignees?: T;
  reporter?: T;
  createdAt?: T;
  updatedAt?: T;
  project?: T;
  labels?:
    | T
    | {
        label?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "types_select".
 */
export interface TypesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
